### ISSUE TITLE
Cannot launch job with current master 

### ISSUE THREAD

**Issue by waliens** [jm-begon/clustertools#14]
The `parse_params` returns ntasks et partition in the `others` dictionnary and makes the call to `run_experiment` fail.
```
Traceback (most recent call last):
  File "features_experiment.py", line 31, in <module>
    run_experiment(experiment, script, script_builder, **other)
TypeError: run_experiment() got an unexpected keyword argument 'ntasks'
```

**Comment by waliens** [comment]
Also:
```
Traceback (most recent call last):
  File "features_experiment.py", line 31, in <module>
    run_experiment(experiment, script, script_builder, **other)
  File "/home/mass/ifilesets/ULG/f035716/miniconda/envs/cytomine/lib/python2.7/site-packages/clustertools/runner.py", line 44, in run_experiment
    for j, (job_name, param) in enumerate(yield_not_done_computation(experiment, user)):
  File "/home/mass/ifilesets/ULG/f035716/miniconda/envs/cytomine/lib/python2.7/site-packages/clustertools/notification.py", line 323, in yield_not_done_computation
    historic = Historic(experiment.name, user)
  File "/home/mass/ifilesets/ULG/f035716/miniconda/envs/cytomine/lib/python2.7/site-packages/clustertools/notification.py", line 205, in __init__
    self.refresh()
  File "/home/mass/ifilesets/ULG/f035716/miniconda/envs/cytomine/lib/python2.7/site-packages/clustertools/notification.py", line 211, in refresh
    queued = frozenset(queued_or_running_jobs(self.user))
TypeError: queued_or_running_jobs() takes no arguments (1 given)
```

**Comment by jm-begon** [comment]
As of 36da01944dfc1afa9a511b551f89500502668774, new master should solve the problem
