### ISSUE TITLE
Different types for one parameter

### ISSUE THREAD

**Issue by vahuynh** [jm-begon/clustertools#38]
An error is returned when launching jobs in which one parameter can be of different types. For example, if the parameter set contains strings and integers, the following error is returned when attempting to launch the jobs:

> Traceback (most recent call last):
  File "run_RSBopt_reg_friedman_5_1000.py", line 135, in <module>
    environment.run(experiment)
  File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/environment.py", line 234, in run
    capacity):
  File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/experiment.py", line 539, in yield_computations
    for j, param_dict in self.parameter_set:
  File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/experiment.py", line 362, in __iter__
    for i, (j, param_dict) in enumerate(self._iter()):
  File "/home/ulg/sysmod/vananh/anaconda3/lib/python3.6/site-packages/clustertools/experiment.py", line 332, in _iter
    ls.sort()
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by jm-begon** [comment]
Ultimately, the problem comes from Python comparison function. One way out would be to provide a custom sorting function in the constructor of the `ParameterSet`.

As a temporary work around, you could use objects of the same nature (say str) and do the casting in the `run` function of the `Computation`.

**Comment by jm-begon** [comment]
Support has been added by @waliens and is now merged is master with  f5557c7
